# permissions for end users to edit imagecollectorresults.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: imagecollectorresult-editor-role
rules:
- apiGroups:
  - eraser.sh
  resources:
  - imagecollectorresults
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - eraser.sh
  resources:
  - imagecollectorresults/status
  verbs:
  - get
