# permissions for end users to view imagecollectorresults.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: imagecollectorresult-viewer-role
rules:
- apiGroups:
  - eraser.sh
  resources:
  - imagecollectorresults
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - eraser.sh
  resources:
  - imagecollectorresults/status
  verbs:
  - get
